import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The Worker holds a closed set of addition phrases so no client-supplied text
/// can reach an image prompt. That set is generated from the catalogue, and it
/// is only safe while the two agree — a missing id means a preview the app
/// offers but the server refuses.
void main() {
  test('worker/src/additions.ts covers every addition in the catalogue', () {
    final generated = File('worker/src/additions.ts');
    expect(generated.existsSync(), isTrue,
        reason: 'run: python3 tool/gen_worker_additions.py');

    final ts = generated.readAsStringSync();
    final catalogue =
        (jsonDecode(File('assets/data/additions.json').readAsStringSync()) as List<dynamic>)
            .cast<Map<String, dynamic>>();

    for (final addition in catalogue) {
      expect(ts, contains('"${addition['id']}":'),
          reason: '${addition['id']} is offered by the app but unknown to the Worker. '
              'Run: python3 tool/gen_worker_additions.py');
    }
  });

  test('it does not contain ids the catalogue has dropped', () {
    final ts = File('worker/src/additions.ts').readAsStringSync();
    final ids =
        (jsonDecode(File('assets/data/additions.json').readAsStringSync()) as List<dynamic>)
            .map((a) => (a as Map<String, dynamic>)['id'] as String)
            .toSet();

    for (final match in RegExp(r'^  "([a-z_0-9]+)":', multiLine: true).allMatches(ts)) {
      expect(ids, contains(match.group(1)),
          reason: '${match.group(1)} is in the Worker but no longer in the catalogue');
    }
  });

  test('the generated file is marked as generated', () {
    // So nobody edits it by hand and has it silently overwritten.
    expect(File('worker/src/additions.ts').readAsStringSync(),
        startsWith('// GENERATED by tool/gen_worker_additions.py'));
  });
}
