// GENERATED by tool/gen_icon_map.py — do not edit.
// Run it again after changing the icon of any food or addition.
import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Every icon name the bundled catalogue refers to.
const Map<String, IconData> kCatalogIcons = {
  'apple': LucideIcons.apple,
  'banana': LucideIcons.banana,
  'bean': LucideIcons.bean,
  'beef': LucideIcons.beef,
  'cake-slice': LucideIcons.cakeSlice,
  'candy': LucideIcons.candy,
  'carrot': LucideIcons.carrot,
  'coffee': LucideIcons.coffee,
  'cookie': LucideIcons.cookie,
  'cooking-pot': LucideIcons.cookingPot,
  'croissant': LucideIcons.croissant,
  'droplet': LucideIcons.droplet,
  'drumstick': LucideIcons.drumstick,
  'egg': LucideIcons.egg,
  'fish': LucideIcons.fish,
  'grape': LucideIcons.grape,
  'ice-cream-bowl': LucideIcons.iceCreamBowl,
  'milk': LucideIcons.milk,
  'nut': LucideIcons.nut,
  'pizza': LucideIcons.pizza,
  'popcorn': LucideIcons.popcorn,
  'salad': LucideIcons.salad,
  'sandwich': LucideIcons.sandwich,
  'soup': LucideIcons.soup,
  'sprout': LucideIcons.sprout,
  'utensils': LucideIcons.utensils,
  'wheat': LucideIcons.wheat,
};

/// The glyph for a catalogue icon name. Unknown names fall back to the same
/// generic one the design uses, so a bad name is a dull icon and never a crash.
IconData catalogIcon(String? name) =>
    kCatalogIcons[name] ?? kCatalogIcons['utensils']!;
