// GENERATED by tool/gen_worker_additions.py — do not edit by hand.
//
// The closed set of things the image model may be asked to add. The API
// takes an id, never a phrase, so no text a client sends can reach the
// prompt. `flutter test` fails if this drifts from additions.json.

export const ADDITION_PHRASES: Readonly<Record<string, string>> = {
  "avocado": "a few slices of avocado",
  "beans": "beans or lentils",
  "boiled_egg": "a boiled egg",
  "cheese_slice": "a slice of cheese",
  "chia": "a spoon of chia seeds",
  "cottage_cheese": "a scoop of cottage cheese",
  "edamame": "a bowl of edamame",
  "frozen_peas": "a scoop of peas",
  "fruit": "a piece of fruit",
  "fuul_side": "a small bowl of fuul",
  "glass_of_milk": "a glass of milk",
  "greek_yogurt": "a bowl of Greek yogurt",
  "grilled_chicken": "a piece of grilled chicken",
  "hummus": "a scoop of hummus",
  "kefir": "a glass of kefir",
  "labneh": "a spoon of labneh",
  "lentil_soup": "a cup of lentil soup",
  "nuts": "a small handful of nuts",
  "oats_stir": "a spoon of oats",
  "olive_oil": "some olive oil",
  "peanut_butter": "a spoon of peanut butter",
  "roast_chickpeas": "roasted chickpeas",
  "sardines": "a tin of sardines",
  "seeds": "some seeds",
  "side_salad": "a side salad",
  "smoked_salmon": "a slice of smoked salmon",
  "tahini": "some tahini",
  "tuna": "a small tin of tuna",
  "veg_side": "a side of cooked vegetables",
  "whole_grain_swap": "whole-grain bread",
  "yogurt": "a small bowl of yogurt",
};
