#!/usr/bin/env python3
"""Generates worker/src/additions.ts from assets/data/additions.json.

The Worker must never interpolate arbitrary text into an image prompt, so it
accepts an addition *id* and looks the phrase up in a closed set. That set has
to match the app's catalogue, and this keeps them in step.

    python3 tool/gen_worker_additions.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
source = json.loads((ROOT / "assets/data/additions.json").read_text())

# "Add a small bowl of yogurt" -> "a small bowl of yogurt": the instruction
# already says "adding one realistic side serving of".
LEAD = re.compile(r"^(add|swap in|stir in|stir through|drizzle over|sprinkle on)\s+", re.I)

entries = []
for item in sorted(source, key=lambda i: i["id"]):
    phrase = LEAD.sub("", item["name"]).strip()
    if not phrase:
        raise SystemExit(f"{item['id']}: name does not read as an instruction")
    entries.append((item["id"], phrase))

lines = [
    "// GENERATED by tool/gen_worker_additions.py — do not edit by hand.",
    "//",
    "// The closed set of things the image model may be asked to add. The API",
    "// takes an id, never a phrase, so no text a client sends can reach the",
    "// prompt. `flutter test` fails if this drifts from additions.json.",
    "",
    "export const ADDITION_PHRASES: Readonly<Record<string, string>> = {",
]
lines += [f"  {id!r}: {phrase!r}," .replace("'", '"') for id, phrase in entries]
lines += ["};", ""]

(ROOT / "worker/src/additions.ts").write_text("\n".join(lines))
print(f"wrote worker/src/additions.ts with {len(entries)} additions")
