#!/usr/bin/env python3
"""Generates the Worker's closed sets from the app's catalogue.

    python3 tool/gen_worker_additions.py

  worker/src/additions.ts   addition id -> the phrase an image prompt may use
  worker/src/foods.ts       food id     -> the name an image prompt may use

The Worker must never interpolate arbitrary text into an image prompt. It takes
*ids* and looks the words up here, so nothing a client sends — or types into
the chat box — can reach a model prompt. Both sets have to match the app's
catalogue, and this keeps them in step.
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
source = json.loads((ROOT / "assets/data/additions.json").read_text())

# "Add a small bowl of yogurt" -> "a small bowl of yogurt": the instruction
# already says "adding one realistic side serving of".
LEAD = re.compile(r"^(add|swap in|stir in|stir through|drizzle over|sprinkle on)\s+", re.I)

entries = []
for item in sorted(source, key=lambda i: i["id"]):
    phrase = LEAD.sub("", item["name"]).strip()
    if not phrase:
        raise SystemExit(f"{item['id']}: name does not read as an instruction")
    entries.append((item["id"], phrase, item.get("tags", []), item.get("cost", 0)))

lines = [
    "// GENERATED by tool/gen_worker_additions.py — do not edit by hand.",
    "//",
    "// The closed set of things the image model may be asked to add. The API",
    "// takes an id, never a phrase, so no text a client sends can reach the",
    "// prompt. `flutter test` fails if this drifts from additions.json.",
    "",
    "export const ADDITION_PHRASES: Readonly<Record<string, string>> = {",
]
lines += [f"  {id!r}: {phrase!r}," .replace("'", '"') for id, phrase, _, _ in entries]
lines += ["};", ""]

# What each addition is, so the Worker can leave out the ones a person has
# said they do not want. The rule lives in the app's engine; these are the
# facts it reasons over, and they have to be the same facts on both sides or
# the AI will suggest a vegetarian a piece of chicken.
lines += [
    "/** Tags and cost, for the same dietary filtering the on-device engine does. */",
    "export const ADDITION_FACTS: Readonly<",
    "  Record<string, { tags: readonly string[]; cost: number }>",
    "> = {",
]
for id, _, tags, cost in entries:
    tag_list = ", ".join(json.dumps(t) for t in tags)
    lines.append(f'  {json.dumps(id)}: {{ tags: [{tag_list}], cost: {cost} }},')
lines += ["};", ""]

(ROOT / "worker/src/additions.ts").write_text("\n".join(lines))
print(f"wrote worker/src/additions.ts with {len(entries)} additions")

# ---------------------------------------------------------------- foods

foods = json.loads((ROOT / "assets/data/foods.json").read_text())
food_entries = [(i["id"], i["name"]) for i in sorted(foods, key=lambda i: i["id"])]

food_lines = [
    "// GENERATED by tool/gen_worker_additions.py — do not edit by hand.",
    "//",
    "// The closed set of foods a prompt may name. Chat is free text, so the",
    "// model returns catalogue *ids* and the image prompt is built from these",
    "// names — never from anything the user typed.",
    "",
    "export const FOOD_NAMES: Readonly<Record<string, string>> = {",
]
food_lines += [f"  {id!r}: {name!r}," .replace("'", '"') for id, name in food_entries]
food_lines += ["};", ""]

(ROOT / "worker/src/foods.ts").write_text("\n".join(food_lines))
print(f"wrote worker/src/foods.ts with {len(food_entries)} foods")
