#!/usr/bin/env python3
"""Generates lib/ui/icons.g.dart — the kebab-case icon names the catalogue uses,
mapped to the Lucide IconData that draws them.

    python3 tool/gen_icon_map.py

Only data-driven names need this. Chrome icons are written as LucideIcons.x
directly in the widgets, where the compiler checks them. These come out of
assets/data/*.json at runtime, so nothing would catch a typo before a user saw
a wrong glyph — hence a generated map, derived from the catalogue rather than
kept by hand, that fails the build instead.
"""
import glob, json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "lib/ui/icons.g.dart"
FALLBACK = "utensils"  # what the design falls back to for an unknown name


def package_names() -> set[str]:
    """Every icon the installed lucide_icons_flutter declares."""
    hits = glob.glob(str(pathlib.Path.home() /
                        ".pub-cache/hosted/*/lucide_icons_flutter-*/lib/lucide_icons.dart"))
    if not hits:
        sys.exit("lucide_icons_flutter not found in the pub cache — run flutter pub get")
    source = pathlib.Path(sorted(hits)[-1]).read_text()
    return set(re.findall(r"static const IconData ([A-Za-z0-9]+)", source))


def camel(kebab: str) -> str:
    head, *rest = kebab.split("-")
    return head + "".join(w[:1].upper() + w[1:] for w in rest)


def main() -> None:
    used = {FALLBACK}
    for name in ("foods", "additions"):
        for item in json.loads((ROOT / f"assets/data/{name}.json").read_text()):
            icon = item.get("icon")
            if not icon:
                sys.exit(f"{name}.json: {item['id']} has no icon")
            used.add(icon)

    available = package_names()
    unknown = sorted(n for n in used if camel(n) not in available)
    if unknown:
        sys.exit(f"Not in lucide_icons_flutter: {unknown}")

    rows = "\n".join(f"  '{n}': LucideIcons.{camel(n)}," for n in sorted(used))
    OUT.write_text(f"""// GENERATED by tool/gen_icon_map.py — do not edit.
// Run it again after changing the icon of any food or addition.
import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Every icon name the bundled catalogue refers to.
const Map<String, IconData> kCatalogIcons = {{
{rows}
}};

/// The glyph for a catalogue icon name. Unknown names fall back to the same
/// generic one the design uses, so a bad name is a dull icon and never a crash.
IconData catalogIcon(String? name) =>
    kCatalogIcons[name] ?? kCatalogIcons['{FALLBACK}']!;
""")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(used)} icons")


if __name__ == "__main__":
    main()
